### ISSUE TITLE
Consumption status of this packer plugin

### ISSUE THREAD

**Issue by thrix** [ppc64le-cloud/packer-plugin-powervs#238]
@mkumatag howdy, we are in desperate need for a packer plugin to create IBM Cloud PowerVS, what is the status of this plugin please? Is it planned IBM will ever support this?

**Comment by mkumatag** [comment]
This project is actively maintained and used in kubernetes ecosystem project for building the images for IBM Cloud PowerVS platform, there is no formal support from IBM company but we can address any issues faced via issues created.

I'm interested in understanding your use case and offering assistance in any way we can.

**Comment by thrix** [comment]
All questions answered privately, thank you
